INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('1', 'Nancy','Paris','2021-01-05 10:30',24,45,61.20);
INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('2', 'Nancy','Luxembourg','2021-01-01 17:30',20,41,31.00);
INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('3', 'Nancy','Paris','2021-01-03 17:30',0,41,31.00);
INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('4', 'Nancy','Paris','2021-01-10 17:30',20,0,31.00);
INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('5', 'Paris','Nancy','2021-01-11 17:30',20,41,31.00);
INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('6', 'Paris','Nancy','2021-01-05 10:30',24,45,61.20);
INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('7', 'Luxembourg','Nancy','2021-01-07 17:30',20,41,31.00);
INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('8', 'Luxembourg','Paris','2021-01-03 17:30',0,41,31.00);
INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('9', 'Luxembourg','Paris','2021-01-10 17:30',20,0,31.00);
INSERT INTO TRAJET(ID, DEPART, ARRIVEE, JOUR, NB_PLACES_COULOIR, NB_PLACES_FENETRE, PRIX) VALUES ('10', 'Paris','Luxembourg','2021-01-12 17:30',20,41,31.00);

INSERT INTO VOYAGEUR(ID, NOM) VALUES ('1', 'BEIRAO');
INSERT INTO VOYAGEUR(ID, NOM) VALUES ('2', 'BOUCHE');
INSERT INTO VOYAGEUR(ID, NOM) VALUES ('3', 'COSSIN');
INSERT INTO VOYAGEUR(ID, NOM) VALUES ('4', 'BARTHELEMY');

INSERT INTO RESERVATION(ID, VOYAGEUR_ID, ALLER_ID, RETOUR_ID, COULOIR, CHOIX_RETOUR, CONFIRME, PAYE) VALUES ('1','1','1','5','1','True','True','False')
INSERT INTO RESERVATION(ID, VOYAGEUR_ID, ALLER_ID, RETOUR_ID, COULOIR, CHOIX_RETOUR, CONFIRME, PAYE)VALUES ('2','1','2',NULL,'1','False','True','False')
INSERT INTO RESERVATION(ID, VOYAGEUR_ID, ALLER_ID, RETOUR_ID, COULOIR, CHOIX_RETOUR, CONFIRME, PAYE) VALUES ('3','1','3',NULL,'0','False','True','False')
INSERT INTO RESERVATION(ID, VOYAGEUR_ID, ALLER_ID, RETOUR_ID, COULOIR, CHOIX_RETOUR, CONFIRME, PAYE) VALUES ('4','1','4',NULL,'1','False','True','False')
INSERT INTO RESERVATION(ID, VOYAGEUR_ID, ALLER_ID, RETOUR_ID, COULOIR, CHOIX_RETOUR, CONFIRME, PAYE) VALUES ('5','1','6',NULL,'2','False','False','False')
INSERT INTO RESERVATION(ID, VOYAGEUR_ID, ALLER_ID, RETOUR_ID, COULOIR, CHOIX_RETOUR, CONFIRME, PAYE) VALUES ('6','2','1','5','1','True','True','False')
INSERT INTO RESERVATION(ID, VOYAGEUR_ID, ALLER_ID, RETOUR_ID, COULOIR, CHOIX_RETOUR, CONFIRME, PAYE) VALUES ('7','3','1',NULL,'0','False','True','False')
INSERT INTO RESERVATION(ID, VOYAGEUR_ID, ALLER_ID, RETOUR_ID, COULOIR, CHOIX_RETOUR, CONFIRME, PAYE) VALUES ('8','3','2','7','1','True','True','False')
INSERT INTO RESERVATION(ID, VOYAGEUR_ID, ALLER_ID, RETOUR_ID, COULOIR, CHOIX_RETOUR, CONFIRME, PAYE) VALUES ('9','2','4','6','1','True','False','False')
